### ISSUE TITLE
Can't create a working custom variable a my dashboard

### ISSUE THREAD

**Issue by fdrouet** [grafana/terraform-provider-schemas#44]
Hello

I try to use `Terraform` and the recently released schemas provider to create all my dashboards on `Grafana Cloud` but i have problem when I want to create custom variable.

I use the following code:

```
resource "grafana_dashboard" "test" {
  provider    = grafana.me
  folder      = grafana_folder.xxxxxx.id
  config_json = data.schemas_core_dashboard.d_test.rendered_json
}

data "schemas_core_dashboard" "d_test" {
  provider      = grafana-schemas
  uid           = "d-tests"
  title         = "Tests"
  editable      = false
  graph_tooltip = 1
  refresh       = "1m"
  time          = {
    from = "now-24h"
  }
  templating = {
    list = [
      {
        name          = "env"
        type          = "custom"
        state         = "pro"
        query         = "dev,ppr,pro"
        skip_url_sync = false
        multi         = false
        hide          = 0
      }
    ]
  }
  panels = []
}
```
As a result, I obtain the Dashboard without error but the dropdown list for `env` is empty (while it seems correct in Settings > Variables screen)

Any idea about what I am doing wrong ?

![image](https://github.com/grafana/terraform-provider-schemas/assets/120171/6d32de7e-2631-458b-bdb4-623e417ea408)

![image](https://github.com/grafana/terraform-provider-schemas/assets/120171/ed5dd165-74bc-4a57-9a7b-b24eca845311)

**Comment by malcolmholmes** [comment]
Can you paste the generated JSON? Especially the bit for the template variables?

**Comment by AgnesToulet** [comment]
Hi! I looked into this and, sadly, this error comes from a bad definition in the schema itself. It has been updated since but this provider was generated based on Grafana 10.0.0 schemas and this has been updated after that. 

I'm planning to work on [this bug](https://github.com/grafana/terraform-provider-schemas/issues/47) that affects quite a lot of attributes and I'll make a new release based on the updated schemas!
